"use client";
import { createTheme, ThemeProvider } from "@material-ui/core";
import CssBaseline from "@material-ui/core/CssBaseline";
import BackgroundVideo from "@/components/background/background";
import NavMenu from "@/components/navigation/navmenu";
import clsx from "clsx";




const theme = createTheme( {
	                           overrides: {
		                           "@global": {
			                           body: {
				                           backgroundColor: "tomato", fontFamily: "'Nirmala UI', sans-serif",
			                           },
		                           },
	                           },
                           } );


// this is the new <Head /> component -
export const metadata = {
	title: "Create Next App", description: "Generated by create next app",
};

export default function RootLayout( { children } ) {
	return ( <html
		
		lang="en"
		className={
			
			clsx( "min-h-screen", "max-w-screen-xl", "overflow-hidden", "overflow-y-auto", "overflow-x-hidden", "bg-gray-100" ) }
	
	>
	<body>
	<CssBaseline/>
	<ThemeProvider theme={ theme }>
		<BackgroundVideo/>
		<NavMenu/>
		{ children }
	</ThemeProvider>
	</body>
	</html> );
}
