
import CssBaseLine from "@ma"

import BackgroundVideo from "@/components/background/background";
import NavMenu from "@/components/navigation/navmenu";




// this is the new <Head /> component -
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout( { children } ) {
	return (
		<html lang="en">
		<body>
		<CssBaseline />
		<BackgroundVideo/>
		<NavMenu/>
		{ children }
		</body>
		</html>
	);
}
