"use client";
import BackgroundVideo from "@/components/background/background";
import NavMenu from "@/components/navigation/navmenu";
import { CacheProvider } from "@chakra-ui/next-js";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import clsx from "clsx";
import { css } from "@emotion/react";
// this is the new <Head /> component -
export const metadata = {
	title: "Create Next App", description: "Generated by create next app",
	link: [ {} ],
};

const colors = {
	brand: {
		900: "#1a365d",
		800: "#153e75",
		700: "#2a69ac",
	},
};



//background-image: url(${ backgroundPoster });

const theme = extendTheme( { colors } );
//background-image: url(${ backgroundPoster });





export default function RootLayout( { children } ) {
	return ( <html
		
		lang="en"
	
	>
	<body>
	<BackgroundVideo/>
	<NavMenu/>
	<CacheProvider>
		<ChakraProvider theme={ theme }>
			{ children }
		</ChakraProvider>
	</CacheProvider>
	
	</body>
	</html> );
}
